<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="castor_mass" value="0.5" />
<xacro:property name="castor_xoff" value="0.0825" />
<xacro:property name="castor_yoff" value="0.0" />


<xacro:macro name="uds_castor" params="prefix">
    <link name="${prefix}castor_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${(wheel_radius-base_height)/2}"/>
        </geometry>
        <material name="dark_gray">
          <color rgba="0.2 0.2 0.2 1"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${(wheel_radius-base_height)/2}"/>
        </geometry>
      </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${castor_mass}"/>
            <inertia
            ixx="${(2.0/5.0) * castor_mass * wheel_radius/2 * wheel_radius/2}" ixy="0" ixz="0"
            iyy="${(2.0/5.0) * castor_mass * wheel_radius/2 * wheel_radius/2}" iyz="0"
            izz="${(2.0/5.0) * castor_mass * wheel_radius/2 * wheel_radius/2}"/>
      </inertial>
    </link>

    <joint name="${prefix}castor_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}castor_link"/>
      <origin xyz="${castor_xoff} ${castor_yoff} ${-(wheel_radius/2 +base_height)}" rpy="0 0 0"/>
    </joint>
</xacro:macro>

</robot>