<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="wheel_radius" value="0.022" />
  <xacro:property name="wheel_offset" value="0.0000" /> 

  <xacro:property name="wheel_separation" value="0.134" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="wheel_mass" value="0.1" />
  <xacro:property name="wheel_xoff" value="0.075" />
  <xacro:property name="wheel_yoff" value="0.070" />

  <xacro:macro name="uds_wheel" params="prefix side x_reflect y_reflect">
    <link name="${prefix}${side}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius + wheel_offset}" length="${wheel_width}"/>
        </geometry>
        <material name="dark_gray">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius + wheel_offset}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${(wheel_mass/12.0) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" ixy="0" ixz="0"
          iyy="${(wheel_mass/2.0) * (wheel_radius*wheel_radius)}" iyz="0"
          izz="${(wheel_mass/12.0) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
      </inertial>
    </link>

    <joint name="${prefix}${side}_wheel_joint" type="continuous">
      <axis xyz="0 1 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}${side}_wheel_link"/>
      <origin xyz="${x_reflect*(wheel_xoff) } ${y_reflect*(wheel_yoff)} 0" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <gazebo reference="base_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="right_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="left_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
  </gazebo>

  <!-- Caster Wheels -->
  <gazebo reference="castor_link">
      <mu1>0.000001</mu1>
      <mu2>0.000001</mu2>
  </gazebo>
</robot>